name: Release workflow
permissions: write-all

on:
  push:
    tags:
      - "v*"
    branches:
      - feat/github-action

jobs:
  release:
    strategy:
      matrix:
        buildTag: ["transtep", "steaming"]

    uses: ./.github/workflows/build-workflow.yml
    name: Build ${{ matrix.buildTag }} binary
    with:
      buildTag: ${{ matrix.buildTag }}
